import { League_Spartan } from "next/font/google";
import '@/public/css/fontawesome-free/css/all.min.css';
import '@/public/css/sb-admin-2.min.css';
import './globals.css';

const league = League_Spartan({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={league.className}>
        {children}
        <script src="/js/jquery.min.js"></script>
        <script src="/js/sb-admin-2.min"></script>
      </body>
    </html>
  );
}
